server:
  port: 9000

spring:
  application:
    name: only-apigateway-service 
  
  cloud:
    gateway:
      routes:
        - id: hello_route # 새로 추가할 라우트의 ID
          uri: http://localhost:8765 # 타겟 서비스의 URI
          predicates:
            - Path=/hello # 매칭할 경로 (정확히 /hello)

          # hello_route
          # 1.http://localhost:9000/hello 로 들어오면
          # 2.http://localhost:8765/hello 로 연결



        - id: abc2hello_route # 새로 추가할 라우트의 ID
          uri: http://localhost:8765 # 타겟 서비스의 URI
          predicates:
            - Path=/abc
          # abc2hello_route
          # 1. http://localhost:9000/abc로 들어오면
          # 2. http://localhost:8765/abc로 연결



        - id: abc2hello_ok_route # 새로 추가할 라우트의 ID
          uri: http://localhost:8765 # 타겟 서비스의 URI
          predicates:
            - Path=/abc
          filters:
            - RewritePath=/abc, /hello
           # abc2hello_ok_route
           # 1. http://localhost:9000/abc로 들어오면
           # 2. 필터에서 abc를 hello로 바꾸면서 설정된 uri로 보냄
           # 3. http://localhost:8765/hello로 연결
